[options]
SudoLoop
Devel
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
CleanAfter
Provides
PgpFetch
CombinedUpgrade
BatchInstall
UpgradeMenu

#UseAsk
#SaveChanges
#RemoveMake
#NewsOnUpgrade
#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache
#SkipReview

#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas
